compile:
	g++ -std=c++17 *.cpp -I/opt/homebrew/include -L/opt/homebrew/lib -I/opt/homebrew/Cellar/postgresql@14/14.17_1/include/postgresql@14 -L/opt/homebrew/Cellar/postgresql@14/14.17_1/lib/postgresql@14 \
	-lPocoNet -lPocoFoundation -lPocoUtil -lPocoNetSSL -lPocoJson -lpq \
	-o proxy_compiled